language: python
python:
- 2.7
- 3.5
- pypy
sudo: false
install:
- pip install -r requirements/testing.txt
- pip install coveralls
script: coverage run --source=autoslug run_tests.py
after_success: coveralls
notifications:
  email:
  - neithere+travis@gmail.com
deploy:
  provider: pypi
  user: __token__
  password:
    secure: RMfytOtUS2SRLhYL2WbUUcoE9Hf51IUh2XjIA0k2hDtjkj/w1LL21W0suvM9rOD8z+gxW8gs/bl3fzTFD/euml3xVuwAxWiyJ8DkvTY13H1nGq4KLKV5OHROkQ09XbtNf8aJB16XC+HE7ezkl4MVBmdvoJse7AJfi+vhJrlDwLkNXLpHzru4Uf3ndImnmF/92nha0c4AF6rN058tWaFyxPcHAjjOgtUG8hMN2Ij6U3qYBeHaSRVRVScu0Qv43jnndAsB9Hpsd5aQe4d5AUblAiuQwFta+27eTdlTOe7s0dzmKWswuaPdzv6ttFAR8zvDGuB5XWEu13wrzwq5m8jUkkaDyU+6FEejT6DGZu5JnuslrahDA/2WCz0nr62Bno4priy9Cny0YcAxSkE2L03ERjWxUvHrVa354lzsAsCJa2w8BZsiSsJFrcjfjGgj3DAxRQA0s1OP4xODkfxEdsisSeCZCpYEa0fc6oePgBpehPJ2AE4Ou/2scWjYeCJ6TrNyW5bpSxPxZOW1Hy5YlSLXkKU6bzOrsXRXs8jujoPTSYrHjZ46W8kkB34X+w88A+IFJDDrNyCuvPC1OeKqo+4IgTS41yGLc+g2RvU5r2TERq/pCwPo16qbGGgvXVwdr2TUJckewcYRqrBJbZb2YqhATYSMCBV+1wJfpJXhArRWbRM=
  on:
    tags: true
